version: '3'
services:
  db:
    image: mariadb
    restart: always
    container_name: dictionary_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dictionary_password
    volumes:
      - ./mysql_db:/var/lib/mysql

networks:
  app-network:
    driver: bridge